### ISSUE TITLE
Crear un evento para las bienvenidas

### ISSUE THREAD

**Issue by jheysonsaav** [HolaMundoDev/discord-bot#1]
crear un evento en el bot que envié un mensaje de bienvenida cada vez que entre un nuevo usuario al servidor, este mensaje debe contener:

- **title:** `¡Bienvenido/a al servidor!`
- **description:** `Hola <@user_id>! Bienvenido/a a Hola Mundo, nos complace tenerte en nuestra comunidad, recuerda leer las <#789293321960554517> para evitar ser advertido. Y no olvides pasar por <#789297714101092393> para dar un pequeño resumen sobre ti.`

este tambien debe contener el avatar del usuario en el "thumbnail" del embed.

**Comment by TeoDev1611** [comment]
Closed by created in #3
