### ISSUE TITLE
Add welcome message

### ISSUE THREAD

**Issue by JheysonDev** [HolaMundoDev/discord-bot#10]
add a welcome message for new server users with the message "¡Hola {usuario}! Bienvenido/a a HolaMundo, nos complace tenerte en nuestra comunidad, recuerda leer las #📜-reglas para evitar ser advertido. Y no olvides pasar por #🤝-introducción para dar un pequeño resumen sobre ti."

**Comment by JheysonDev** [comment]
the name of the user and the channels must be mentioned "reglas" and "introducción"

**Comment by TeoDev1611** [comment]
This is added in the pull request #16
