### ISSUE TITLE
 Define the technologies to use

### ISSUE THREAD

**Issue by JheysonDev** [HolaMundoDev/discord-bot#6]
I open this issue to define the technologies to use in the project such as:

- The programming language

**Comment by JheysonDev** [comment]
.

**Comment by JheysonDev** [comment]
..

**Comment by JheysonDev** [comment]
.

**Comment by TeoDev1611** [comment]
Python para que todos puedan contribuir

**Comment by JheysonDev** [comment]
@TeoDev1611 This issue has already been closed due to internal decision-making
